.TH MRESETZ 1 2023-May "" "measures qubit, returns result (and resets it to |0> before deallocation)"
.SH NAME
MResetZ \- MResetZ(q)
.SH SYNOPSIS
\fIMResetZ(q)\fR
.SH OPTIONS
.PP
\fBq\fB \fR\- . a qubit
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.MResetZ at Q.R:line 5
.PP
.SH COPYRIGHT
Copyright © Who wrote it, What license is it under? Licensed 2023
